import { Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body className={poppins.className}>
        <header>
          <Navigation />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
