import { Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body className={`${poppins.className} bg-background-color-primary`}>
        <header>
          <Navigation />
        </header>
        <main className="m-10">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
