const simonData = [
  {
    name: "area-alt",
    shortDesc: "Ensures <area> elements of image maps have alternate text ",
    longDesc: "",
    impact: "Critical",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "aria-allowed-attr",
    shortDesc: "Ensures an element's role supports its ARIA attributes",
    longDesc: "",
    impact: "Critical",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "area-alt",
    shortDesc: "Ensures <area> elements of image maps have alternate text ",
    longDesc: "",
    impact: "Critical",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "aria-allowed-attr",
    shortDesc: "Ensures an element's role supports its ARIA attributes",
    longDesc: "",
    impact: "Critical",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "aria-braille-equivalent",
    shortDesc: "Ensure aria-braillelabel and aria-brailleroledescription have a non-braille equivalent",
    longDesc: "",
    impact: "Serious",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "aria-conditional-attr",
    shortDesc: "Ensures ARIA attributes are used as described in the specification of the element's role",
    longDesc: "",
    impact: "Serious",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "aria-deprecated-role",
    shortDesc: "Ensures elements do not use deprecated roles",
    longDesc: "",
    impact: "Minor",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
  {
    name: "form-field-multiple-labels",
    shortDesc: "Ensures form field does not have multiple label elements",
    longDesc: "",
    impact: "Moderate",
    whyDesc: "",
    imgPath: "",
    imgAlt: "",
    imgPath2: "",
    imgAlt2: "",
    affect: ["", "", "", ""],
  },
];
export default simonData;